# Valores em Base64:
#   petvida123  -> 
#   root123     -> 
#   petvida-k8s-secret -> 
apiVersion: v1
kind: Secret
metadata:
  name: petvida-secret
  namespace: petvida
type: Opaque
data:
  DB_PASSWORD: 
  MYSQL_ROOT_PASSWORD: 
  SECRET_KEY: 
