apiVersion: v1
kind: Secret
metadata:
  name: petvida-secret
  namespace: petvida
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: root123
  MYSQL_DATABASE: petvida_db
  MYSQL_USER: usuario
  MYSQL_PASSWORD: senha123
